"use client";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import type { Order } from "@/types";

export function OrdersPanel({initial,userId}:{initial:Order[];userId:string}){
 const [items,setItems]=useState(initial);
 function replace(order:Order){setItems(v=>v.map(x=>x.id===order.id?order:x))}
 async function action(order:Order,name:string){try{if(name==="review"){const rating=Number(prompt("Rating from 1 to 5"));if(!rating)return;const comment=prompt("Optional review comment")||null;await api("/reviews",{method:"POST",body:{order_id:order.id,rating,comment}});toast.success("Review published");return}const r=await api<Order|{message:string}>(`/orders/${order.id}/${name}`,{method:"POST"});if("id" in r)replace(r);toast.success("Order updated")}catch(e){toast.error(e instanceof Error?e.message:"Action failed")}}
 async function pickup(order:Order){try{const d=await api<{pickup_address:string;contact_phone?:string;delivery_notes?:string}>(`/listings/${order.listing.id}/pickup-details`);alert(`Pickup: ${d.pickup_address}\nPhone: ${d.contact_phone||"Not provided"}\nNotes: ${d.delivery_notes||"None"}`)}catch(e){toast.error(e instanceof Error?e.message:"Details unavailable")}}
 if(!items.length)return <div className="empty"><h2>No food requests</h2><p className="muted">Requests you send or receive will appear here.</p></div>;
 return <div className="stack">{items.map(o=>{const provider=o.provider.id===userId;const party=provider?o.requester:o.provider;return <article key={o.id} className="card" style={{padding:22}}><div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><span className="badge badgeMuted">{o.status}</span><h3>{o.listing.title}</h3><p className="muted">{provider?"Requested by":"Provided by"} {party.display_name} · {o.quantity} {o.listing.unit} · {o.fulfillment_method}</p>{o.message&&<p>{o.message}</p>}</div><strong>{Number(o.agreed_price).toLocaleString("en-BD")} BDT</strong></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{provider&&o.status==="REQUESTED"&&<><button className="button buttonPrimary" onClick={()=>action(o,"accept")}>Accept</button><button className="button buttonDanger" onClick={()=>action(o,"reject")}>Reject</button></>}{provider&&o.status==="ACCEPTED"&&<button className="button buttonCream" onClick={()=>action(o,"ready")}>Mark ready</button>}{["ACCEPTED","READY"].includes(o.status)&&<><button className="button buttonPrimary" onClick={()=>action(o,"confirm-completion")}>Confirm completion</button><button className="button buttonGhost" onClick={()=>pickup(o)}>Pickup details</button></>}{["REQUESTED","ACCEPTED","READY"].includes(o.status)&&<button className="button buttonDanger" onClick={()=>action(o,"cancel")}>Cancel</button>}{o.status==="COMPLETED"&&<button className="button buttonGhost" onClick={()=>action(o,"review")}>Leave review</button>}</div></article>})}</div>
}
