"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Camera, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import type { UserMe } from "@/types";
import { UserAvatar } from "@/components/user-avatar";

export function ProfileForm({ user }: { user: UserMe }) {
  const router=useRouter();
  const [current,setCurrent]=useState(user); const [busy,setBusy]=useState(false); const [preview,setPreview]=useState<string|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{let updated=await api<UserMe>("/users/profile",{method:"PATCH",body:{username:form.get("username"),display_name:form.get("display_name"),phone:form.get("phone")||null,bio:form.get("bio")||null,city:form.get("city")||null,area:form.get("area")||null}});const avatar=form.get("avatar");if(avatar instanceof File&&avatar.size>0){const body=new FormData();body.set("file",avatar);updated=await api<UserMe>("/users/avatar",{method:"POST",body})}setCurrent(updated);setPreview(null);toast.success("Profile updated");router.refresh()}catch(caught){toast.error(caught instanceof Error?caught.message:"Unable to update profile")}finally{setBusy(false)}}
  return <form className="card stack" style={{padding:26}} onSubmit={submit}><div style={{display:"flex",alignItems:"center",gap:16,flexWrap:"wrap"}}>{preview?<span style={{width:64,height:64,borderRadius:20,overflow:"hidden",display:"block"}}><img src={preview} alt="New profile preview" style={{width:"100%",height:"100%",objectFit:"cover"}}/></span>:<UserAvatar user={current} size="lg"/>}<div className="field" style={{flex:"1 1 260px"}}><label htmlFor="avatar"><Camera size={16} style={{verticalAlign:"-3px",marginRight:6}}/>Profile photo</label><input className="input" id="avatar" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event)=>{const file=event.target.files?.[0];setPreview(file?URL.createObjectURL(file):null)}}/><span className="help">JPEG, PNG or WebP, maximum 5 MB. A square photo works best.</span></div></div><div className="formGrid"><div className="field"><label>Name</label><input className="input" name="display_name" defaultValue={current.display_name} required/></div><div className="field"><label>Username</label><input className="input" name="username" defaultValue={current.username} minLength={3} maxLength={30} pattern="[a-zA-Z0-9_]+" required/></div><div className="field"><label>Email</label><input className="input" value={current.email} disabled/></div><div className="field"><label>Phone</label><input className="input" name="phone" defaultValue={current.phone??""}/></div><div className="field"><label>City</label><input className="input" name="city" defaultValue={current.city??""}/></div><div className="field"><label>Area</label><input className="input" name="area" defaultValue={current.area??""}/></div><div className="field full"><label>Bio</label><textarea className="textarea" name="bio" defaultValue={current.bio??""}/></div></div><button className="button buttonPrimary" disabled={busy}>{busy?<><Loader2 size={17} className="spin"/>Saving…</>:"Save profile"}</button></form>;
}
