"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { api } from "@/lib/api";

export function RegisterForm(){
  const router=useRouter();const [step,setStep]=useState<1|2>(1);const [email,setEmail]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function requestOtp(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{await api("/auth/request-registration-otp",{method:"POST",body:{email}});setStep(2)}catch(e){setError(e instanceof Error?e.message:"Unable to send code")}finally{setBusy(false)}}
  async function register(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload={email,otp:f.get("otp"),password:f.get("password"),display_name:f.get("display_name"),city:f.get("city")||null,area:f.get("area")||null};const response=await fetch("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok){setError(data.detail??"Registration failed");setBusy(false);return}router.push("/dashboard");router.refresh()}
  if(step===1)return <form className="stack" onSubmit={requestOtp}>{error&&<div className="error">{error}</div>}<div className="field"><label htmlFor="registerEmail">Email</label><input id="registerEmail" className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><span className="help">We will send a six-digit verification code.</span></div><button className="button buttonPrimary" disabled={busy}>{busy?"Sending…":"Send verification code"}</button></form>;
  return <form className="stack" onSubmit={register}>{error&&<div className="error">{error}</div>}<div className="success">Code sent to {email}</div><div className="field"><label htmlFor="otp">Verification code</label><input id="otp" className="input" name="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></div><div className="field"><label htmlFor="display_name">Your name</label><input id="display_name" className="input" name="display_name" minLength={2} required/></div><div className="formGrid"><div className="field"><label htmlFor="city">City</label><input id="city" className="input" name="city"/></div><div className="field"><label htmlFor="area">Area</label><input id="area" className="input" name="area"/></div></div><div className="field"><label htmlFor="newPassword">Password</label><input id="newPassword" className="input" name="password" type="password" minLength={8} required/><span className="help">At least 8 characters with uppercase, lowercase and a number.</span></div><button className="button buttonPrimary" disabled={busy}>{busy?"Creating account…":"Create account"}</button><button className="button buttonGhost" type="button" onClick={()=>setStep(1)}>Use another email</button></form>
}
